## Numpy array axis in case of 3D array

In [4]:
import numpy as np

In [11]:
np_array_1 = np.arange(0,27).reshape(3,3,3)
np_array_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
np_array_2 = np.arange(27,54).reshape(3,3,3)
np_array_2

array([[[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [25]:
result_arr = np_array_1 + np_array_2
result_arr

array([[[27, 29, 31],
        [33, 35, 37],
        [39, 41, 43]],

       [[45, 47, 49],
        [51, 53, 55],
        [57, 59, 61]],

       [[63, 65, 67],
        [69, 71, 73],
        [75, 77, 79]]])

In [26]:
result_arr.shape

(3, 3, 3)

In [27]:
result_arr[0]

array([[27, 29, 31],
       [33, 35, 37],
       [39, 41, 43]])

In [31]:
result_arr[0].shape

(3, 3)

In [29]:
result_arr[1]

array([[45, 47, 49],
       [51, 53, 55],
       [57, 59, 61]])

In [32]:
result_arr[1].shape

(3, 3)

In [22]:
result_arr[2]

array([[63, 65, 67],
       [69, 71, 73],
       [75, 77, 79]])

In [33]:
result_arr[2].shape

(3, 3)

### When axis is 0
- The sum of inner array will happen element wise for example 
        [[ 0,  1,  2],        [[ 9, 10, 11],      [[18, 19, 20],
        [ 3,  4,  5],    +    [12, 13, 14],   +   [21, 22, 23],
        [ 6,  7,  8]]         [15, 16, 17]]       [24, 25, 26]]
    The three inner arrays will be summed element wise like 
    - 1+9+18 = 27
    - 1+10+19 = 30

In [42]:
np_array_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
axis_0_sum = np.sum(np_array_1,axis=0)
axis_0_sum

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

### When axis is 1
- The sum will happen column wise in each inner matrix and the result of that sum will be saved in the resultant array

In [38]:
np_array_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
axis_1_sum = np.sum(np_array_1,axis=1)
axis_1_sum

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

### When axis is 2
- The sum will happen row wise in each inner matrix and the result of that sum will be saved in the resultant array

In [40]:
np_array_1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
axis_1_sum = np.sum(np_array_1,axis=2)
axis_1_sum

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])