In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## The simple way to iterate through the array is using for loop:

### This will print all the rows in the array

In [4]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


### This will print all the elements in the array using a for loop

In [5]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### If you want to flatten a numpy array into a list and then print all the elements then you can do this

#### This way you won't have to write two for loops. Since the flatten function already converts a 2D array into a 1D array hence the inner forloop is not required anymore only one for loop will suffice.

In [9]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### There is another way to iterate through numpy array using nditer
#### If you use np.nditer(a,order='c'). Then it will have the same effect as if you have flatten the 2D array into a 1D array and then looped over it to print the elements in each cells.
- One thing to remember is that it will print the cells row wise meaning first it will print the first row, second row, third row and so on.
#### If you use np.nditer(d,order='F'). Then it will have the same effect as if you have flatten the 2D array into a 1D array and then looped over it to print the elements in each cells.
- One thing to remember is that it will print the cells column wise meaning first it will print the first column, second column, third column and so on.

In [25]:
print(f"original array ===> \n {a}")
for x in np.nditer(a,order='c'):
    print(f"{x} <==> {x.shape}")

original array ===> 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 <==> ()
1 <==> ()
2 <==> ()
3 <==> ()
4 <==> ()
5 <==> ()
6 <==> ()
7 <==> ()
8 <==> ()
9 <==> ()
10 <==> ()
11 <==> ()


In [26]:
print(f"original array ===> \n {a}")
for x in np.nditer(a,order='F'):
    print(f"{x} <==> {x.shape}")

original array ===> 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0 <==> ()
4 <==> ()
8 <==> ()
1 <==> ()
5 <==> ()
9 <==> ()
2 <==> ()
6 <==> ()
10 <==> ()
3 <==> ()
7 <==> ()
11 <==> ()


### When you set the flag external_loop, instead of yielding individual scalar values (zero-dimensional), nditer yields 1D arrays (vectors) — i.e., it gives you a batch of values at a time.
### Why/When to use external_loop?
- Performance: Reduces Python-level loop overhead by yielding chunks instead of scalars.
- Use-case: When you want to operate on slices (e.g., rows) at once.

In [27]:
print(f"original array ===> \n {a}")
for x in np.nditer(a,order="C",flags=['external_loop']):
    print(f"{x} <==> {x.shape}")

original array ===> 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11] <==> (12,)


In [28]:
print(f"original array ===> \n {a}")
for x in np.nditer(a,order="F",flags=['external_loop']):
    print(f"{x} <==> {x.shape}")

original array ===> 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 4 8] <==> (3,)
[1 5 9] <==> (3,)
[ 2  6 10] <==> (3,)
[ 3  7 11] <==> (3,)
